---
extends: default

rules:
  # 120 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1 # Default is 2, but YAMl VSCode extension formats with 1
