---

name: Portman tests on pull request
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:

  functional-tests:
    name: Portman tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Portman
        run: npm install -g @apideck/portman

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman OpenAPI reporter
        # https://github.com/NickHeap2/newman-reporter-openapi
        run: npm install -g newman-reporter-openapi

      - name: Verify Review App status
        id: review_app_status
        uses: niteoweb/reviewapps-deploy-status@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # yamllint disable rule:line-length
      - name: Verify implementation is in sync with API
        run: |
          portman \
            --cliOptionsFile portman/portman-cli.json \
            -b ${{ steps.review_app_status.outputs.review_app_url }}/v2 \
            --newmanRunOptions '{"reporters":["cli","junit","openapi"],"reporter":{"junit":{"export":"portman/output/newman/"},"openapi":{"spec":"openapi.yaml","serverUrl":"${{ steps.review_app_status.outputs.review_app_url }}/v2","reportstyle":"tall"}}}'
      # yamllint enable rule:line-length

      - name: Upload generated Postman test collection
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: postman-collection
          path: portman/output/postman/

      - name: Upload Portman test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: portman-junit-report
          path: portman/output/newman/

      - name: Publish Portman test results inline
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: portman/output/newman/*.xml
          check_name: Portman Test Results
